<?php
  return $infoRestaurants = [
    [
      'name' => 'O\' ZOO',
      'address' => 'Via San Biagio, 5',
      'description' => 'Pub/Pizzeria, Prodotti home-made, Birre artigianali',
      'img_path' => 'https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600',
      'PIVA' => '12345678912',
      'opening_time' => '12:00',
      'closing_time' => '22:00',
    ],
    [
      'name' => 'Hostaria al Boschetto',
      'address' => 'Via del Boschetto, 30',
      'description' => 'Tovaglie quadrettate e pareti colorate in un ristorante rustico con specialità romanesche e giardino interno',
      'img_path' => 'https://media-cdn.tripadvisor.com/media/photo-s/0f/6f/c6/32/giardino-interno-all.jpg',
      'PIVA' => '12345678915',
      'opening_time' => '12:00',
      'closing_time' => '22:00',
    ],
    [
      'name' => 'Matermatuta',
      'address' => 'Via Milano, 50',
      'description' => 'Piatti di pesce dallo stile creativo, in spazi eleganti dall\'arredamento bicolore con dettagli contemporanei.',
      'img_path' => 'https://res.cloudinary.com/tf-lab/image/upload/w_600,h_337,c_fill,g_auto:subject,q_auto,f_auto/restaurant/8da794d3-040d-4b6d-af42-7840edb2eefc/4b7c15b2-8a09-4617-8ea4-7117975ba183.jpg',
      'PIVA' => '12815618915',
      'opening_time' => '10:00',
      'closing_time' => '22:00',
    ],
    [
      'name' => 'Ristorante Mirabelle',
      'address' => 'Via di Porta Pinciana, 14',
      'description' => 'Elegante ristorante a lume di candela in hotel lussuoso, che offre cucina italiana ricercata e un romantico panorama.',
      'img_path' => 'https://res.cloudinary.com/tf-lab/image/upload/w_600,h_337,c_fill,g_auto:subject,q_auto,f_auto/restaurant/22312b41-46de-4057-9853-af63a7c199bb/b7e18a87-1693-4569-a393-28d58480d584.jpg',
      'PIVA' => '12815667915',
      'opening_time' => '12:30',
      'closing_time' => '22:30',
    ],
    [
      'name' => 'Il Pagliaccio',
      'address' => 'Via dei Banchi Vecchi, 129',
      'description' => 'Il ristorante Il Pagliaccio dello Chef Anthony Genovese si trova a Roma e propone cucina raffinata, unica e inequivocabile, una vera esperienza di gusto. A disposizione del cliente un menù creativo e ricco.',
      'img_path' => 'https://media-cdn.tripadvisor.com/media/photo-s/15/86/86/ff/dettagli-sala-nuova.jpg',
      'PIVA' => '12813612915',
      'opening_time' => '12:00',
      'closing_time' => '14:30',
    ],
    [
      'name' => 'La Pergola - Rome Cavalieri',
      'address' => 'Via Alberto Cadlolo, 101',
      'description' => 'Noto ristorante in hotel di lusso con vista sulla città dal tetto, che serve cucina italiana gourmet.',
      'img_path' => 'https://michaelromei.files.wordpress.com/2011/06/pergola.jpg',
      'PIVA' => '33815618915',
      'opening_time' => '19:30',
      'closing_time' => '22:30',
    ],
    [
      'name' => 'Pascucci al Porticciolo',
      'address' => 'Viale Traiano, 85',
      'description' => 'Pietanze di pesce d\'autore in un moderno e raffinato locale con abat-jour di design e quadri contemporanei.',
      'img_path' => 'https://i1.wp.com/www.menudiroma.com/wp-content/uploads/2015/04/pascucci-al-porticciolo.jpg?fit=800%2C530&ssl=1',
      'PIVA' => '12813648516',
      'opening_time' => '13:00',
      'closing_time' => '22:30',
    ],
    [
      'name' => 'Idylio by Apreda',
      'address' => 'Via di S. Chiara, 4/A',
      'description' => 'Il ristorante Idylio by Apreda è una vera e propria enclave gourmet, intima e riservata. Qui i sapori mediterranei si fondono alla perfezione con lo spirito internazionale tipico di una metropoli da sempre al centro del mondo. Per questo abbiamo scelto uno chef di straordinario livello, interprete di una cucina in grado di soddisfare anche i palati più esigenti.',
      'img_path' => 'https://www.ticati.com/img/hotel/10083743s.jpg',
      'PIVA' => '12111118915',
      'opening_time' => '19:30',
      'closing_time' => '22:30',
    ],
    [
      'name' => 'Metamorfosi',
      'address' => 'Via Giovanni Antonelli, 30',
      'description' => 'Piatti italiani gourmet in un ristorante su 2 piani dalle linee geometriche e dal design contemporaneo.',
      'img_path' => 'https://www.scattidigusto.it/wp-content/uploads/2016/01/Metamorfosi-Roma.jpg',
      'PIVA' => '11814618925',
      'opening_time' => '12:30',
      'closing_time' => '22:30',
    ],
    [
      'name' => 'Pipero Roma',
      'address' => 'Corso Vittorio Emanuele II, 250',
      'description' => 'Piatti italiani d\'alta cucina serviti tra sofisticati arredi contemporanei in un ristorante stellato.',
      'img_path' => 'https://res.cloudinary.com/tf-lab/image/upload/restaurant/d1078921-d7b3-4d40-a839-fabb3717aab3/2dc64f18-28e9-4db3-9872-cd3270e21495.jpg',
      'PIVA' => '12815228225',
      'opening_time' => '12:00',
      'closing_time' => '18:00',
    ]
  ];