<?php 

  return $plates = [
    [
      [
        'name' => 'Mood',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Lattuga, Pomodoro, Cheddar, Bacon, Anelli di cipolla',
        'price' => '7',
        'img_path' => 'https://wips.plug.it/cips/buonissimo.org/cms/2019/03/hamburger.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Nevada',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Lattuga, Pomodoro, Mozzarella, Bacon',
        'price' => '7',
        'img_path' => 'https://cdn.ilclubdellericette.it/wp-content/uploads/2018/02/ricetta-hamburger.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Oklahoma',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Pomodoro, Caciocavallo, Gorgonzola, Emmenthal, Cheddar, Bacon',
        'price' => '7',
        'img_path' => 'https://www.confoodential.it/wp-content/uploads/2018/11/hamburger-gourmet.x19848.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Texas',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Pomodoro, Bacon, Emmenthal, Salsa piccante',
        'price' => '8',
        'img_path' => 'https://www.unamericanaincucina.com/wp-content/uploads/2014/02/MG_5882.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Arizona',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Lattuga, Gorgonzola, Cipolla agrodolce, Bacon, Salsa piccante',
        'price' => '8.5',
        'img_path' => 'https://www.mrdoyle.it/wp-content/uploads/2019/01/AdobeStock_209775207-scaled-e1575394210352.jpeg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '0',
      ],
    ],

    [
      [
        'name' => 'Bombolotti alla gricia',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://blog.giallozafferano.it/primipiattiricette/wp-content/uploads/2017/04/La-Gricia.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Rigatoni all\' amatriciana',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Guanciale, Pecorino, Salsa di pomodoro, Peperoncino',
        'price' => '9.5',
        'img_path' => 'https://www.conad.it/content/dam/conad/conad-consumer/ricette/DayOne%20Ricette/S&D/S&D_BucatiniAmatriciana.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '0',
      ],
      [
        'name' => 'Rigatoni alla carbonara',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Uova, Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://www.negroni.com/sites/negroni.com/files/styles/scale__1440_x_1440_/public/carbonara_la_pasta_amata.jpg?itok=Iz2Me_rw',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Tonnarelli cacio e pepe',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Tonnarelli, Pecorino, Pepe nero',
        'price' => '11',
        'img_path' => 'https://www.ilgustonline.com/wp-content/uploads/2020/07/47DFE942-04F8-4EF3-A02A-A2C8708E42D8.jpeg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Fusilli del boschetto',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Fusilli, Guanciale, Grana, Funghi porcini, Rucola',
        'price' => '12',
        'img_path' => 'https://blog.giallozafferano.it/unvegetarianoperamico/wp-content/uploads/2018/05/fusil.png',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

    [
      [
        'name' => 'Gnocchi alla rapa rossa',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Gnocchi, Rapa rossa, Vongole, Calamari, Asparagi',
        'price' => '16',
        'img_path' => 'https://www.ricettedalmondo.it/images/foto-ricette/g/29442-gnocchi-ai-frutti-di-mare.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Pennoni all\' amatriciana di tonno',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Pennoni, Tonno, Salsa di pomodoro, Peperoncino',
        'price' => '16',
        'img_path' => 'https://i0.wp.com/www.pescenudo.it/wp-content/uploads/2011/01/pennette-allamatriciana-di-tonno1.jpg?ssl=1',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '0',
      ],
      [
        'name' => 'I Sapori della mia Terra',
        'description' => 'I piselli gli ho sbucciati personalmente ieri sera',
        'ingredients' => 'Gnocchetti, Ricotta, Vellutata di piselli e speck',
        'price' => '12',
        'img_path' => 'http://media.tvblog.it/b/b38/020_masterchefitalia6.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Riso Acquerello',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Riso, Frutti di mare, Limone, Zucchine',
        'price' => '20',
        'img_path' => 'https://blog.giallozafferano.it/cuinalory/wp-content/uploads/2016/08/risotto-con-zucchine-frutti-di-mare-e-curcuma.jpg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Rigatoni alla carbonara',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Uova, Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://www.negroni.com/sites/negroni.com/files/styles/scale__1440_x_1440_/public/carbonara_la_pasta_amata.jpg?itok=Iz2Me_rw',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

    [
      [
        'name' => 'Gnocchi alla rapa rossa',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Gnocchi, Rapa rossa, Vongole, Calamari, Asparagi',
        'price' => '16',
        'img_path' => 'https://www.ricettedalmondo.it/images/foto-ricette/g/29442-gnocchi-ai-frutti-di-mare.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Pennoni all\' amatriciana di tonno',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Pennoni, Tonno, Salsa di pomodoro, Peperoncino',
        'price' => '16',
        'img_path' => 'https://i0.wp.com/www.pescenudo.it/wp-content/uploads/2011/01/pennette-allamatriciana-di-tonno1.jpg?ssl=1',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '0',
      ],
      [
        'name' => 'I Sapori della mia Terra',
        'description' => 'I piselli gli ho sbucciati personalmente ieri sera',
        'ingredients' => 'Gnocchetti, Ricotta, Vellutata di piselli e speck',
        'price' => '12',
        'img_path' => 'http://media.tvblog.it/b/b38/020_masterchefitalia6.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Oklahoma',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Pomodoro, Caciocavallo, Gorgonzola, Emmenthal, Cheddar, Bacon',
        'price' => '7',
        'img_path' => 'https://www.confoodential.it/wp-content/uploads/2018/11/hamburger-gourmet.x19848.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Rigatoni alla carbonara',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Uova, Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://www.negroni.com/sites/negroni.com/files/styles/scale__1440_x_1440_/public/carbonara_la_pasta_amata.jpg?itok=Iz2Me_rw',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

    [
      [
        'name' => 'Rigatoni all\' amatriciana',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Guanciale, Pecorino, Salsa di pomodoro, Peperoncino',
        'price' => '9.5',
        'img_path' => 'https://www.conad.it/content/dam/conad/conad-consumer/ricette/DayOne%20Ricette/S&D/S&D_BucatiniAmatriciana.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Fusilli del boschetto',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Fusilli, Guanciale, Grana, Funghi porcini, Rucola',
        'price' => '12',
        'img_path' => 'https://blog.giallozafferano.it/unvegetarianoperamico/wp-content/uploads/2018/05/fusil.png',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Mood',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Lattuga, Pomodoro, Cheddar, Bacon, Anelli di cipolla',
        'price' => '7',
        'img_path' => 'https://wips.plug.it/cips/buonissimo.org/cms/2019/03/hamburger.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Bombolotti alla gricia',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://blog.giallozafferano.it/primipiattiricette/wp-content/uploads/2017/04/La-Gricia.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Rigatoni alla carbonara',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Uova, Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://www.negroni.com/sites/negroni.com/files/styles/scale__1440_x_1440_/public/carbonara_la_pasta_amata.jpg?itok=Iz2Me_rw',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

    [
      [
        'name' => 'Gnocchi alla rapa rossa',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Gnocchi, Rapa rossa, Vongole, Calamari, Asparagi',
        'price' => '16',
        'img_path' => 'https://www.ricettedalmondo.it/images/foto-ricette/g/29442-gnocchi-ai-frutti-di-mare.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Pennoni all\' amatriciana di tonno',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Pennoni, Tonno, Salsa di pomodoro, Peperoncino',
        'price' => '16',
        'img_path' => 'https://i0.wp.com/www.pescenudo.it/wp-content/uploads/2011/01/pennette-allamatriciana-di-tonno1.jpg?ssl=1',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '0',
      ],
      [
        'name' => 'I Sapori della mia Terra',
        'description' => 'I piselli gli ho sbucciati personalmente ieri sera',
        'ingredients' => 'Gnocchetti, Ricotta, Vellutata di piselli e speck',
        'price' => '12',
        'img_path' => 'http://media.tvblog.it/b/b38/020_masterchefitalia6.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '0',
      ],
      [
        'name' => 'Tonnarelli cacio e pepe',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Tonnarelli, Pecorino, Pepe nero',
        'price' => '11',
        'img_path' => 'https://www.ilgustonline.com/wp-content/uploads/2020/07/47DFE942-04F8-4EF3-A02A-A2C8708E42D8.jpeg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Arizona',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Lattuga, Gorgonzola, Cipolla agrodolce, Bacon, Salsa piccante',
        'price' => '8.5',
        'img_path' => 'https://www.mrdoyle.it/wp-content/uploads/2019/01/AdobeStock_209775207-scaled-e1575394210352.jpeg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

    [
      [
        'name' => 'Gnocchi alla rapa rossa',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Gnocchi, Rapa rossa, Vongole, Calamari, Asparagi',
        'price' => '16',
        'img_path' => 'https://www.ricettedalmondo.it/images/foto-ricette/g/29442-gnocchi-ai-frutti-di-mare.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Pennoni all\' amatriciana di tonno',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Pennoni, Tonno, Salsa di pomodoro, Peperoncino',
        'price' => '16',
        'img_path' => 'https://i0.wp.com/www.pescenudo.it/wp-content/uploads/2011/01/pennette-allamatriciana-di-tonno1.jpg?ssl=1',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'I Sapori della mia Terra',
        'description' => 'I piselli gli ho sbucciati personalmente ieri sera',
        'ingredients' => 'Gnocchetti, Ricotta, Vellutata di piselli e speck',
        'price' => '12',
        'img_path' => 'http://media.tvblog.it/b/b38/020_masterchefitalia6.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '0',
      ],
      [
        'name' => 'Riso Acquerello',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Riso, Frutti di mare, Limone, Zucchine',
        'price' => '20',
        'img_path' => 'https://blog.giallozafferano.it/cuinalory/wp-content/uploads/2016/08/risotto-con-zucchine-frutti-di-mare-e-curcuma.jpg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Rigatoni alla carbonara',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Uova, Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://www.negroni.com/sites/negroni.com/files/styles/scale__1440_x_1440_/public/carbonara_la_pasta_amata.jpg?itok=Iz2Me_rw',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

    [
      [
        'name' => 'Bombolotti alla gricia',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://blog.giallozafferano.it/primipiattiricette/wp-content/uploads/2017/04/La-Gricia.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Rigatoni all\' amatriciana',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Guanciale, Pecorino, Salsa di pomodoro, Peperoncino',
        'price' => '9.5',
        'img_path' => 'https://www.conad.it/content/dam/conad/conad-consumer/ricette/DayOne%20Ricette/S&D/S&D_BucatiniAmatriciana.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '0',
      ],
      [
        'name' => 'Rigatoni alla carbonara',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Uova, Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://www.negroni.com/sites/negroni.com/files/styles/scale__1440_x_1440_/public/carbonara_la_pasta_amata.jpg?itok=Iz2Me_rw',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Tonnarelli cacio e pepe',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Tonnarelli, Pecorino, Pepe nero',
        'price' => '11',
        'img_path' => 'https://www.ilgustonline.com/wp-content/uploads/2020/07/47DFE942-04F8-4EF3-A02A-A2C8708E42D8.jpeg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Fusilli del boschetto',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Fusilli, Guanciale, Grana, Funghi porcini, Rucola',
        'price' => '12',
        'img_path' => 'https://blog.giallozafferano.it/unvegetarianoperamico/wp-content/uploads/2018/05/fusil.png',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

    [
      [
        'name' => 'Gnocchi alla rapa rossa',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Gnocchi, Rapa rossa, Vongole, Calamari, Asparagi',
        'price' => '16',
        'img_path' => 'https://www.ricettedalmondo.it/images/foto-ricette/g/29442-gnocchi-ai-frutti-di-mare.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '0',
      ],
      [
        'name' => 'Pennoni all\' amatriciana di tonno',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Pennoni, Tonno, Salsa di pomodoro, Peperoncino',
        'price' => '16',
        'img_path' => 'https://i0.wp.com/www.pescenudo.it/wp-content/uploads/2011/01/pennette-allamatriciana-di-tonno1.jpg?ssl=1',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'I Sapori della mia Terra',
        'description' => 'I piselli gli ho sbucciati personalmente ieri sera',
        'ingredients' => 'Gnocchetti, Ricotta, Vellutata di piselli e speck',
        'price' => '12',
        'img_path' => 'http://media.tvblog.it/b/b38/020_masterchefitalia6.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Riso Acquerello',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Riso, Frutti di mare, Limone, Zucchine',
        'price' => '20',
        'img_path' => 'https://blog.giallozafferano.it/cuinalory/wp-content/uploads/2016/08/risotto-con-zucchine-frutti-di-mare-e-curcuma.jpg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Rigatoni alla carbonara',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Uova, Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://www.negroni.com/sites/negroni.com/files/styles/scale__1440_x_1440_/public/carbonara_la_pasta_amata.jpg?itok=Iz2Me_rw',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

    [
      [
        'name' => 'Gnocchi alla rapa rossa',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Gnocchi, Rapa rossa, Vongole, Calamari, Asparagi',
        'price' => '16',
        'img_path' => 'https://www.ricettedalmondo.it/images/foto-ricette/g/29442-gnocchi-ai-frutti-di-mare.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Pennoni all\' amatriciana di tonno',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Pennoni, Tonno, Salsa di pomodoro, Peperoncino',
        'price' => '16',
        'img_path' => 'https://i0.wp.com/www.pescenudo.it/wp-content/uploads/2011/01/pennette-allamatriciana-di-tonno1.jpg?ssl=1',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'I Sapori della mia Terra',
        'description' => 'I piselli gli ho sbucciati personalmente ieri sera',
        'ingredients' => 'Gnocchetti, Ricotta, Vellutata di piselli e speck',
        'price' => '12',
        'img_path' => 'http://media.tvblog.it/b/b38/020_masterchefitalia6.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Riso Acquerello',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Riso, Frutti di mare, Limone, Zucchine',
        'price' => '20',
        'img_path' => 'https://blog.giallozafferano.it/cuinalory/wp-content/uploads/2016/08/risotto-con-zucchine-frutti-di-mare-e-curcuma.jpg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Rigatoni alla carbonara',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Uova, Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://www.negroni.com/sites/negroni.com/files/styles/scale__1440_x_1440_/public/carbonara_la_pasta_amata.jpg?itok=Iz2Me_rw',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

  ];

?>