<?php 

  return $plates = [
    [
      [
        'name' => 'Pizza Margherita',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Pomodoro, Mozzarella, Basilico fresco',
        'price' => '8',
        'img_path' => 'https://www.scattidigusto.it/wp-content/uploads/2018/03/pizza-margherita-originale-Scatti-di-Gusto.jpg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Nevada',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Lattuga, Pomodoro, Mozzarella, Bacon',
        'price' => '7',
        'img_path' => 'https://cdn.ilclubdellericette.it/wp-content/uploads/2018/02/ricetta-hamburger.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Oklahoma',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Pomodoro, Caciocavallo, Gorgonzola, Emmenthal, Cheddar, Bacon',
        'price' => '7',
        'img_path' => 'https://www.confoodential.it/wp-content/uploads/2018/11/hamburger-gourmet.x19848.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Texas',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Pomodoro, Bacon, Emmenthal, Salsa piccante',
        'price' => '8',
        'img_path' => 'https://www.unamericanaincucina.com/wp-content/uploads/2014/02/MG_5882.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Arizona',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Lattuga, Gorgonzola, Cipolla agrodolce, Bacon, Salsa piccante',
        'price' => '8.5',
        'img_path' => 'https://www.mrdoyle.it/wp-content/uploads/2019/01/AdobeStock_209775207-scaled-e1575394210352.jpeg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '0',
      ],
    ],

    [
      [
        'name' => 'Bombolotti alla gricia',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://blog.giallozafferano.it/primipiattiricette/wp-content/uploads/2017/04/La-Gricia.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Rigatoni alla carbonara',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Uova, Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://www.negroni.com/sites/negroni.com/files/styles/scale__1440_x_1440_/public/carbonara_la_pasta_amata.jpg?itok=Iz2Me_rw',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Tonnarelli cacio e pepe',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Tonnarelli, Pecorino, Pepe nero',
        'price' => '11',
        'img_path' => 'https://www.ilgustonline.com/wp-content/uploads/2020/07/47DFE942-04F8-4EF3-A02A-A2C8708E42D8.jpeg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Fusilli del boschetto',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Fusilli, Guanciale, Grana, Funghi porcini, Rucola',
        'price' => '12',
        'img_path' => 'https://blog.giallozafferano.it/unvegetarianoperamico/wp-content/uploads/2018/05/fusil.png',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Ramen',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Spaghetti, Brodo di carne, Miso, Guarnizioni di maiale affettato',
        'price' => '9.5',
        'img_path' => 'https://cdn.ilclubdellericette.it/wp-content/uploads/2020/01/ramen-giapponese.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '0',
      ],
    ],

    [
      [
        'name' => 'Torta Cioccolato e Amarene',
        'description' => 'Pasta lievitata al cioccolato fondente 70% Guanaja, farcita con amarene candite',
        'ingredients' => 'Ingredienti non disponibili',
        'price' => '18',
        'img_path' => 'https://www.agrodolce.it/app/uploads/2017/12/091-17-Torta-con-amarene-e-cioccolato.jpg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Nevada',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Lattuga, Pomodoro, Mozzarella, Bacon',
        'price' => '7',
        'img_path' => 'https://cdn.ilclubdellericette.it/wp-content/uploads/2018/02/ricetta-hamburger.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'I Sapori della mia Terra',
        'description' => 'I piselli gli ho sbucciati personalmente ieri sera',
        'ingredients' => 'Gnocchetti, Ricotta, Vellutata di piselli e speck',
        'price' => '12',
        'img_path' => 'http://media.tvblog.it/b/b38/020_masterchefitalia6.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Riso Acquerello',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Riso, Frutti di mare, Limone, Zucchine',
        'price' => '20',
        'img_path' => 'https://blog.giallozafferano.it/cuinalory/wp-content/uploads/2016/08/risotto-con-zucchine-frutti-di-mare-e-curcuma.jpg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Rigatoni alla carbonara',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Uova, Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://www.negroni.com/sites/negroni.com/files/styles/scale__1440_x_1440_/public/carbonara_la_pasta_amata.jpg?itok=Iz2Me_rw',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

    [
      [
        'name' => 'Gnocchi alla rapa rossa',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Gnocchi, Rapa rossa, Vongole, Calamari, Asparagi',
        'price' => '16',
        'img_path' => 'https://i.ytimg.com/vi/sYGFF6AI4Wc/maxresdefault.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Nevada',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Lattuga, Pomodoro, Mozzarella, Bacon',
        'price' => '7',
        'img_path' => 'https://cdn.ilclubdellericette.it/wp-content/uploads/2018/02/ricetta-hamburger.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'I Sapori della mia Terra',
        'description' => 'I piselli gli ho sbucciati personalmente ieri sera',
        'ingredients' => 'Gnocchetti, Ricotta, Vellutata di piselli e speck',
        'price' => '12',
        'img_path' => 'http://media.tvblog.it/b/b38/020_masterchefitalia6.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Torta Tiramisù',
        'description' => 'Con caffè espresso e crema al mascarpone',
        'ingredients' => 'Ingredienti non disponibili',
        'price' => '18',
        'img_path' => 'https://blog.giallozafferano.it/dulcisinforno/wp-content/uploads/2020/05/Torta-tiramisu-7747.jpg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Rigatoni alla carbonara',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Uova, Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://www.negroni.com/sites/negroni.com/files/styles/scale__1440_x_1440_/public/carbonara_la_pasta_amata.jpg?itok=Iz2Me_rw',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

    [
      [
        'name' => 'Ramen',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Spaghetti, Brodo di carne, Miso, Guarnizioni di maiale affettato',
        'price' => '9.5',
        'img_path' => 'https://cdn.ilclubdellericette.it/wp-content/uploads/2020/01/ramen-giapponese.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '0',
      ],
      [
        'name' => 'Fusilli del boschetto',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Fusilli, Guanciale, Grana, Funghi porcini, Rucola',
        'price' => '12',
        'img_path' => 'https://blog.giallozafferano.it/unvegetarianoperamico/wp-content/uploads/2018/05/fusil.png',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Mood',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Lattuga, Pomodoro, Cheddar, Bacon, Anelli di cipolla',
        'price' => '7',
        'img_path' => 'https://wips.plug.it/cips/buonissimo.org/cms/2019/03/hamburger.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Bombolotti alla gricia',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://blog.giallozafferano.it/primipiattiricette/wp-content/uploads/2017/04/La-Gricia.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Rigatoni alla carbonara',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Uova, Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://www.negroni.com/sites/negroni.com/files/styles/scale__1440_x_1440_/public/carbonara_la_pasta_amata.jpg?itok=Iz2Me_rw',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

    [
      [
        'name' => 'Gnocchi alla rapa rossa',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Gnocchi, Rapa rossa, Vongole, Calamari, Asparagi',
        'price' => '16',
        'img_path' => 'https://i.ytimg.com/vi/sYGFF6AI4Wc/maxresdefault.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Nevada',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Lattuga, Pomodoro, Mozzarella, Bacon',
        'price' => '7',
        'img_path' => 'https://cdn.ilclubdellericette.it/wp-content/uploads/2018/02/ricetta-hamburger.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'I Sapori della mia Terra',
        'description' => 'I piselli gli ho sbucciati personalmente ieri sera',
        'ingredients' => 'Gnocchetti, Ricotta, Vellutata di piselli e speck',
        'price' => '12',
        'img_path' => 'http://media.tvblog.it/b/b38/020_masterchefitalia6.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '0',
      ],
      [
        'name' => 'Tonnarelli cacio e pepe',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Tonnarelli, Pecorino, Pepe nero',
        'price' => '11',
        'img_path' => 'https://www.ilgustonline.com/wp-content/uploads/2020/07/47DFE942-04F8-4EF3-A02A-A2C8708E42D8.jpeg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Arizona',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Lattuga, Gorgonzola, Cipolla agrodolce, Bacon, Salsa piccante',
        'price' => '8.5',
        'img_path' => 'https://www.mrdoyle.it/wp-content/uploads/2019/01/AdobeStock_209775207-scaled-e1575394210352.jpeg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

    [
      [
        'name' => 'Nachos Cucaracha',
        'description' => 'Triangolini di mais fritti con formaggio grattugiato, fagioli, pico de gallo - cipolla, coriandolo e lime - , fagioli, panna acida - da scaldare al microonde',
        'ingredients' => 'Ingredienti non disponibili',
        'price' => '12.5',
        'img_path' => 'https://d2sj0xby2hzqoy.cloudfront.net/kenwood_italy/attachments/data/000/004/331/medium/ricetta-nachos-con-carne-piccante.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Nevada',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Hamburger di Manzo, Lattuga, Pomodoro, Mozzarella, Bacon',
        'price' => '7',
        'img_path' => 'https://cdn.ilclubdellericette.it/wp-content/uploads/2018/02/ricetta-hamburger.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Pizza Margherita',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Pomodoro, Mozzarella, Basilico fresco',
        'price' => '8',
        'img_path' => 'https://www.scattidigusto.it/wp-content/uploads/2018/03/pizza-margherita-originale-Scatti-di-Gusto.jpg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Sushi Royal',
        'description' => 'La box perfetta per gli amanti di Sushi e Sashimi, 33 pezzi misti.',
        'ingredients' => 'Ingredienti non disponibili',
        'price' => '45',
        'img_path' => 'https://www.ilgiornaledelcibo.it/wp-content/uploads/2017/10/sushi-1.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Rigatoni alla carbonara',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Rigatoni, Uova, Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://www.negroni.com/sites/negroni.com/files/styles/scale__1440_x_1440_/public/carbonara_la_pasta_amata.jpg?itok=Iz2Me_rw',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

    [
      [
        'name' => 'Bombolotti alla gricia',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Guanciale, Pecorino, Pepe Nero',
        'price' => '9.5',
        'img_path' => 'https://blog.giallozafferano.it/primipiattiricette/wp-content/uploads/2017/04/La-Gricia.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Ramen',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Spaghetti, Brodo di carne, Miso, Guarnizioni di maiale affettato',
        'price' => '9.5',
        'img_path' => 'https://cdn.ilclubdellericette.it/wp-content/uploads/2020/01/ramen-giapponese.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '0',
      ],
      [
        'name' => 'Sushi Royal',
        'description' => 'La box perfetta per gli amanti di Sushi e Sashimi, 33 pezzi misti.',
        'ingredients' => 'Ingredienti non disponibili',
        'price' => '45',
        'img_path' => 'https://www.ilgiornaledelcibo.it/wp-content/uploads/2017/10/sushi-1.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '0',
      ],
      [
        'name' => 'Tonnarelli cacio e pepe',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Tonnarelli, Pecorino, Pepe nero',
        'price' => '11',
        'img_path' => 'https://www.ilgustonline.com/wp-content/uploads/2020/07/47DFE942-04F8-4EF3-A02A-A2C8708E42D8.jpeg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Fusilli del boschetto',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Fusilli, Guanciale, Grana, Funghi porcini, Rucola',
        'price' => '12',
        'img_path' => 'https://blog.giallozafferano.it/unvegetarianoperamico/wp-content/uploads/2018/05/fusil.png',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

    [
      [
        'name' => 'Wakame',
        'description' => 'insalata di alghe giapponesi in agrodolce con sesamo',
        'ingredients' => 'Ingredienti non disponibili',
        'price' => '4.5',
        'img_path' => 'https://i.ytimg.com/vi/sYGFF6AI4Wc/maxresdefault.jpg',
        'vegan' => '1',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Sushi Royal',
        'description' => 'La box perfetta per gli amanti di Sushi e Sashimi, 33 pezzi misti.',
        'ingredients' => 'Ingredienti non disponibili',
        'price' => '45',
        'img_path' => 'https://www.ilgiornaledelcibo.it/wp-content/uploads/2017/10/sushi-1.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Pizza Margherita',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Pomodoro, Mozzarella, Basilico fresco',
        'price' => '8',
        'img_path' => 'https://www.scattidigusto.it/wp-content/uploads/2018/03/pizza-margherita-originale-Scatti-di-Gusto.jpg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Riso Acquerello',
        'description' => 'Descrizione non disponibile',
        'ingredients' => 'Riso, Frutti di mare, Limone, Zucchine',
        'price' => '20',
        'img_path' => 'https://blog.giallozafferano.it/cuinalory/wp-content/uploads/2016/08/risotto-con-zucchine-frutti-di-mare-e-curcuma.jpg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Nachos Cucaracha',
        'description' => 'Triangolini di mais fritti con formaggio grattugiato, fagioli, pico de gallo - cipolla, coriandolo e lime - , fagioli, panna acida - da scaldare al microonde',
        'ingredients' => 'Ingredienti non disponibili',
        'price' => '12.5',
        'img_path' => 'https://d2sj0xby2hzqoy.cloudfront.net/kenwood_italy/attachments/data/000/004/331/medium/ricetta-nachos-con-carne-piccante.jpg',
        'vegan' => '0',
        'vegetarian' => '0',
        'spicy' => '1',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

    [
      [
        'name' => 'Torta al limoncello',
        'description' => 'Farcita con crema al limoncello e bucce di Limone Costa d’Amalfi',
        'ingredients' => 'Ingredienti non disponibili',
        'price' => '18',
        'img_path' => 'https://www.paneangelicdn.it/media/uploads/recipe/5cd04da26d7e0_torta-al-limoncello-a-misura.jpg',
        'vegan' => '1',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Torta Tiramisù',
        'description' => 'Con caffè espresso e crema al mascarpone',
        'ingredients' => 'Ingredienti non disponibili',
        'price' => '18',
        'img_path' => 'https://blog.giallozafferano.it/dulcisinforno/wp-content/uploads/2020/05/Torta-tiramisu-7747.jpg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
      [
        'name' => 'Torta alle Mandorle',
        'description' => '
        Farcita con bucce d’arancia candite e glassa di mandorle',
        'ingredients' => 'Ingredienti non disponibili',
        'price' => '18',
        'img_path' => 'https://www.dolcidessert.it/wp-content/uploads/bfi_thumb/torta-alle-mandorle-37pwcx1kzzhvzxu4mbcg7e.jpg',
        'vegan' => '1',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Torta Cioccolato e Amarene',
        'description' => 'Pasta lievitata al cioccolato fondente 70% Guanaja, farcita con amarene candite',
        'ingredients' => 'Ingredienti non disponibili',
        'price' => '18',
        'img_path' => 'https://www.agrodolce.it/app/uploads/2017/12/091-17-Torta-con-amarene-e-cioccolato.jpg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '1',
        'available' => '1',
      ],
      [
        'name' => 'Torta Ricotta e Pere',
        'description' => 'Soffice pasta lievitata farcita con pere candite e crema di ricotta profumata al rhum e nocciole',
        'ingredients' => 'Ingredienti non disponibili',
        'price' => '18',
        'img_path' => 'https://loves.cucchiaio.it/wp-content/uploads/2017/05/Torta-ricotta-e-pere.jpg',
        'vegan' => '0',
        'vegetarian' => '1',
        'spicy' => '0',
        'glutenfree' => '0',
        'available' => '1',
      ],
    ],

  ];

?>